### ISSUE TITLE
本文の　[型引数の制約] (２９％辺り) の説明文に間違いがある

### ISSUE THREAD

**Issue by sasasa** [autumn009/TanoCSharpSamples#1]
> class 　 B < T >　 where 　 T 　:　 A 　 これ で 型 引数 T には 必ず CallT メソッド が ある こと が 保証 さ れ、 呼び出し 可能 になり ます。

↓
×「必ず CallT メソッド」
〇「必ず Hello メソッド」

**Comment by autumn009** [comment]
レポートありがとうございます。次版2.05で直ります。
