### ISSUE TITLE
本文の [文字 を 置き換える Replace メソッド] (32％辺り) の説明文に間違いがある

### ISSUE THREAD

**Issue by sasasa** [autumn009/TanoCSharpSamples#2]
> たとえば、【* くん、* くん。 僕 の 名前 は* だろ?】 の* を【 たろ う】 に 置き換え て【 たろ うく ん、 たろ うく ん。 君 の 名前 は たろ う だろ?】

僕か君かどちらかに統一
下のソースコードでは「君の名前は」となっている

**Comment by autumn009** [comment]
レポートありがとうございます。次版2.05で君に統一します。
