### ISSUE TITLE
[本文] 2進数から10進数へ [42%]

### ISSUE THREAD

**Issue by sasasa** [autumn009/TanoCSharpSamples#4]
> ● 1 桁 目 + 2 桁 目 × 2 + 3 桁 目 × 4 + 4 桁 目 × 8 + 5 桁 目 × 16 + 6 桁 目 × 32 + 7 桁 目 × 4 + 64 桁 目 × 128

1 桁 目 + 
2 桁 目 × 2 + 
3 桁 目 × 4 + 
4 桁 目 × 8 + 
5 桁 目 × 16 + 
6 桁 目 × 32 + 
7 桁 目 × 4 + 64 桁 目 × 128  ←ここが間違い

**Comment by autumn009** [comment]
レポートありがとうございます。次版2.05で直ります。
