### ISSUE TITLE
[問題文] C29Q2 の回答と説明文の不整合

### ISSUE THREAD

**Issue by sasasa** [autumn009/TanoCSharpSamples#7]
http://minitext1.azurewebsites.net/?filename=TanoCSharp&section=C29Q2
回答は5でコンパイルエラーになる。と書いてあるが。

問題文では4がビルドエラー
5が実行時に例外で止まる
となっている。

**Comment by autumn009** [comment]
レポートありがとうございます。解答サーバのテキストを修正しました。
